# docker-compose.production.yml

version: '3.8'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: vlados1206/taski_backend
    env_file: .env
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,130.193.54.163,taski1206.hopto.org,.hopto.org,172.18.0.2,172.18.0.3
    volumes:
      - static_volume:/backend_static

  frontend:
    image: vlados1206/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: vlados1206/taski_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80